name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        # need to find a way to test all of them
        for dir in `ls`
        do
          if [ -d "$dir" ]; then
            cd "$dir"
            cargo build --verbose
            cargo test --verbose
          fi
        done
        # add some unit tests later
