name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        # need to find a way to test all of them
        cd hello-cargo
        cargo build --verbose
        cargo test --verbose
        # add some unit tests later
        cd ../guessing-game
        cargo build --verbose
        cargo test --verbose
